apiVersion: v1
kind: Service
metadata:
  name: gtime
  labels:
    app: gtime
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 31200
  selector:
    app: gtime
